name: "P6 GHA: PR Title Linter"
description: "P6 GHA: PR Title Linter"
author: "Philip M. Gollucci"

runs:
  using: "composite"
  steps:
    - uses: amannn/action-semantic-pull-request@v6.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        types: |-
          chore
          ci
          feat
          fix
          merge queue
        requireScope: false
