name: "P6 GHA: PR Title Linter"
description: "P6 GHA: PR Title Linter"
author: "Philip M. Gollucci"

inputs:
  gh_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Lint PR Title
      uses: amannn/action-semantic-pull-request@v6.1.1
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      with:
        types: |-
          chore
          ci
          feat
          fix
          merge queue
          major
        requireScope: false
